"use client";

import { CloudSun } from "lucide-react";
import { Suspense, useState, type ReactElement } from "react";

import { ChartSkeleton } from "@/components/charts/ChartSkeleton";
import { EnergyFlowDiagram } from "@/components/dashboard/EnergyFlowDiagram";
import { GlidepathCard } from "@/components/dashboard/GlidepathCard";
import { InvertersCard } from "@/components/dashboard/InvertersCard";
import { DynamicLiveEnergyChart } from "@/components/dashboard/LiveEnergyChart.dynamic";
import { MarketDistribution } from "@/components/market/MarketDistribution";
import { MarketEventLog } from "@/components/market/MarketEventLog";
import { MarketInfo } from "@/components/market/MarketInfo";
import { MarketInsights } from "@/components/market/MarketInsights";
import { DynamicMarketPriceChart } from "@/components/market/MarketPriceChart.dynamic";
import { MarketSummaryCard } from "@/components/market/MarketSummaryCard";
import { PreviewSidebar, type PreviewKey } from "@/components/sections/preview/PreviewSidebar";
import {
  SNAPSHOT_DASHBOARD_DATA,
  SNAPSHOT_MARKET_DATA,
  SNAPSHOT_PRODUCTION_DATA,
} from "@/lib/demo/landing-snapshot";

import BrowserBar from "../dashboard/BrowserBar";

/**
 * Hero browser-mockup preview. A self-contained, client-side "embedded
 * product preview": `PreviewSidebar` (a marketing-only visual copy of the
 * real `AppSidebar`, not the real component) switches which panel is shown
 * below purely via local React state — the browser window itself never
 * navigates anywhere. Each panel reuses the real presentational Dashboard/
 * Market components fed a frozen, one-time snapshot of real production data
 * (`lib/demo/landing-snapshot.ts`, generated by
 * `scripts/create-landing-snapshot.ts` — see that script's doc comment).
 * This file never fetches data, calls Huawei/ENTSO-E, or touches a
 * database — it only imports literal, already-computed values. BESS and
 * Automations have no reusable presentational component yet, so those two
 * panels are small static blocks matching the real product's own "honestly
 * unavailable"/preview conventions.
 *
 * The whole sidebar+content canvas renders at a real, natural desktop size
 * and is scaled down with a CSS transform to fit the hero's fixed-width
 * mockup frame — a real screenshot's proportions, not the actual layout
 * being squeezed through narrower responsive breakpoints.
 */

const data = SNAPSHOT_DASHBOARD_DATA;
const market = SNAPSHOT_MARKET_DATA;
const production = SNAPSHOT_PRODUCTION_DATA;

const CANVAS_WIDTH = 1440;
// +~13% over the original 860px canvas — same width, same SCALE (no zoom
// change), just more vertical room so cards breathe like the real app.
const CANVAS_HEIGHT = 970;
const SCALE = 980 / CANVAS_WIDTH;

const currentPriceTrend = { direction: "up" as const, label: "+4.20 EUR/MWh" };

const nowAnnotation =
  data.energyFlow.available && production.currentExport.available
    ? `${data.energyFlow.pvKw} kW prod · ${production.currentExport.kw} kW export`
    : undefined;

/**
 * Landing-page-only weather summary — same card shell/eyebrow style as the
 * real `WeatherCard` (`rounded-2xl border border-white/10 bg-white/[0.03]`,
 * `CloudSun` eyebrow), but not that component: the real product genuinely
 * has no weather integration yet ("Weather integration coming soon."), and
 * this snapshot must not misrepresent that. Frozen, static operational
 * copy only — no chart, no large icon, no live data.
 */
function WeatherSummaryPanel() {
  const rows: Array<{ label: string; value: string; note?: string }> = [
    { label: "Solar Irradiation", value: "≈ 3.0 kWh/m²" },
    { label: "Cloud Cover", value: "56–91%", note: "High cloud cover reducing PV output." },
    { label: "Module Temperature", value: "24–26°C", note: "Optimal operating temperature." },
    { label: "Wind", value: "4–6 km/h", note: "Natural cooling of PV modules." },
    { label: "Rain", value: "Light showers", note: "Temporary production reduction, while naturally cleaning the panels." },
  ];

  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4 shadow-[0_1px_0_0_rgba(255,255,255,0.03)_inset,0_12px_28px_-16px_rgba(0,0,0,0.55)]">
      <p className="flex items-center gap-1.5 text-[11px] font-medium uppercase tracking-wider text-slate-500">
        <CloudSun className="h-3.5 w-3.5" />
        Weather
      </p>

      <div className="mt-3 space-y-2.5">
        {rows.map((row) => (
          <div key={row.label}>
            <div className="flex items-center justify-between text-xs">
              <span className="text-slate-500">{row.label}</span>
              <span className="text-slate-300">{row.value}</span>
            </div>
            {row.note && <p className="mt-0.5 text-[11px] text-slate-600">{row.note}</p>}
          </div>
        ))}
      </div>
    </div>
  );
}

function DashboardPanel() {
  return (
    <div className="mr-auto max-w-7xl space-y-3">
      <section className="grid gap-2.5 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-6">
        <MarketSummaryCard eyebrow="Yield Today" value={data.kpis.producedTodayKwh?.toFixed(1)} valueUnit="kWh" />
        <MarketSummaryCard eyebrow="Total Yield" value={data.kpis.totalYieldKwh ? (data.kpis.totalYieldKwh / 1000).toFixed(1) : undefined} valueUnit="MWh" />
        <MarketSummaryCard eyebrow="Consumption Today" value={data.kpis.consumedTodayKwh?.toFixed(1)} valueUnit="kWh" />
        <MarketSummaryCard eyebrow="Consumed from PV" value={data.kpis.consumedFromPvKwh?.toFixed(1)} valueUnit="kWh" />
        <MarketSummaryCard eyebrow="Fed to Grid" value={data.kpis.exportedTodayKwh?.toFixed(1)} valueUnit="kWh" />
        <MarketSummaryCard eyebrow="From Grid" value={data.kpis.importedTodayKwh?.toFixed(1)} valueUnit="kWh" />
      </section>

      <section className="grid gap-2.5 lg:grid-cols-[30%_1fr]">
        <div className="flex flex-col rounded-2xl border border-white/10 bg-white/[0.03] p-3.5 shadow-[0_1px_0_0_rgba(255,255,255,0.03)_inset,0_12px_28px_-16px_rgba(0,0,0,0.55)] sm:p-4">
          <div>
            <h2 className="text-sm font-semibold text-white">System Overview</h2>
            <p className="mt-0.5 text-xs text-slate-500">Real-time energy flow</p>
          </div>
          <div className="mt-2 min-h-0 flex-1">
            <EnergyFlowDiagram flow={data.energyFlow} isToday={data.isToday} />
          </div>
        </div>

        <div className="flex flex-col rounded-2xl border border-white/10 bg-white/[0.03] p-3.5 shadow-[0_1px_0_0_rgba(255,255,255,0.03)_inset,0_12px_28px_-16px_rgba(0,0,0,0.55)] sm:p-4">
          <div>
            <h2 className="text-sm font-semibold text-white">Live Energy</h2>
            <p className="mt-0.5 text-xs text-slate-500">Today&apos;s production, consumption, and grid exchange</p>
          </div>
          <div className="mt-2.5 h-[320px]">
            <Suspense fallback={<ChartSkeleton />}>
              <DynamicLiveEnergyChart data={data.chartSeries} nowAnnotation={data.nowAnnotation} />
            </Suspense>
          </div>
        </div>
      </section>

      <section className="grid gap-2.5 lg:grid-cols-2 xl:grid-cols-4">
        <InvertersCard inverters={data.inverters} />
        <WeatherSummaryPanel />
        <GlidepathCard />
        <MarketEventLog entries={data.eventLog} />
      </section>
    </div>
  );
}

function MarketPanel() {
  return (
    <div className="mr-auto max-w-7xl space-y-3">
      <section className="grid gap-2.5 sm:grid-cols-2 xl:grid-cols-5">
        <MarketSummaryCard
          eyebrow="Today's Revenue"
          value={data.kpis.revenue.available ? data.kpis.revenue.revenueEur.toFixed(2) : undefined}
          valueUnit="EUR"
          rows={
            data.kpis.revenue.available
              ? [
                  { label: "Exported today", value: `${data.kpis.revenue.exportedKwh.toFixed(2)} kWh` },
                  {
                    label: "Average selling price",
                    value:
                      data.kpis.revenue.averagePriceEurPerMwh !== null
                        ? `${data.kpis.revenue.averagePriceEurPerMwh.toFixed(2)} EUR/MWh`
                        : "—",
                  },
                ]
              : undefined
          }
        />

        <MarketSummaryCard
          eyebrow="Current Price"
          value={market.summary.currentPrice?.value.toString()}
          valueUnit="EUR/MWh"
          caption={market.summary.currentPrice?.intervalLabel}
          trend={currentPriceTrend}
        />

        <MarketSummaryCard
          eyebrow="Current Export"
          value={production.currentExport.available ? production.currentExport.kw.toString() : undefined}
          valueUnit="kW"
        />

        <MarketSummaryCard
          eyebrow="Configured Mode"
          statusDot={{
            colorClass: production.configuredExportModeLabel.colorClass,
            label: production.configuredExportModeLabel.label,
          }}
          rows={[{ label: "Source", value: "Huawei configuration endpoint" }]}
        />

        <MarketSummaryCard
          eyebrow="Threshold"
          value={market.threshold.minimumExportPrice.toString()}
          valueUnit={`${market.threshold.currency}/MWh`}
          caption="Minimum profitable price"
          statusDot={{
            colorClass: market.summary.marketStatus.healthy ? "bg-emerald-400" : "bg-red-400",
            label: market.summary.marketStatus.healthy ? "Healthy" : "Degraded",
          }}
        />
      </section>

      <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-3.5 shadow-[0_1px_0_0_rgba(255,255,255,0.03)_inset,0_12px_28px_-16px_rgba(0,0,0,0.55)] sm:p-4">
        <div>
          <h2 className="text-sm font-semibold text-white">Price &amp; Export</h2>
          <p className="mt-0.5 text-xs text-slate-500">Electricity price and recommended export windows</p>
        </div>

        <div className="mt-2.5 h-[260px]">
          <Suspense fallback={<ChartSkeleton />}>
            <DynamicMarketPriceChart
              series={market.series}
              thresholdPrice={market.threshold.minimumExportPrice}
              nowAnnotation={nowAnnotation}
              settlementEnergySeries={production.settlementEnergySeries.map(({ intervalStart, exportedKwh }) => ({
                intervalStart,
                exportedKwh,
              }))}
              installedCapacityKw={production.installedCapacityKw}
            />
          </Suspense>
        </div>
      </section>

      <section className="grid gap-2.5 lg:grid-cols-2 xl:grid-cols-4">
        <MarketEventLog entries={market.eventLog} />
        <MarketInsights insights={market.insights} />
        <MarketDistribution buckets={market.distribution} />
        <MarketInfo country={market.summary.marketStatus.country} source={market.summary.marketStatus.source} lastUpdateLabel={null} />
      </section>
    </div>
  );
}

function BessPanel() {
  return (
    <div className="mr-auto max-w-7xl">
      <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4 shadow-[0_1px_0_0_rgba(255,255,255,0.03)_inset,0_12px_28px_-16px_rgba(0,0,0,0.55)]">
        <p className="text-[11px] font-medium uppercase tracking-wider text-slate-500">Status</p>
        <p className="mt-3 text-sm text-slate-400">No battery systems connected.</p>
        <p className="mt-1 max-w-md text-xs text-slate-600">
          Voltessa automatically detects and manages battery assets when available.
        </p>
      </div>
    </div>
  );
}

/** Static, non-interactive toggle — presentation only, no state, no handler. */
function PreviewToggle({ label, on }: { label: string; on: boolean }) {
  return (
    <div className="flex items-center justify-between rounded-xl border border-white/10 bg-white/5 px-4 py-3">
      <span className="text-sm text-white/80">{label}</span>
      <span
        className={`relative inline-flex h-6 w-11 shrink-0 items-center rounded-full transition ${
          on ? "bg-emerald-400/80" : "bg-slate-600"
        }`}
      >
        <span
          className={`inline-block h-5 w-5 transform rounded-full bg-white transition ${
            on ? "translate-x-5" : "translate-x-0.5"
          }`}
        />
      </span>
    </div>
  );
}

function AutomationsPanel() {
  return (
    <div className="mr-auto max-w-7xl">
      <section className="rounded-2xl border border-white/10 bg-white/5 p-6">
        <h2 className="text-lg font-medium text-white">Automation Controls</h2>
        <p className="mt-2 text-sm text-white/60">Platform automation capabilities for this plant.</p>

        <div className="mt-6 space-y-3">
          <PreviewToggle label="Grid Export Limit" on={true} />
          <PreviewToggle label="Production Curtailment" on={false} />
        </div>

        <p className="mt-4 text-xs text-slate-500">
          Preview only — not connected to a real plant in this snapshot.
        </p>
      </section>
    </div>
  );
}

function AlertsPanel() {
  return (
    <div className="mr-auto max-w-7xl">
      <section>
        <p className="text-white/60">Review operational alerts and important platform events.</p>
      </section>
    </div>
  );
}

const PANELS: Record<PreviewKey, () => ReactElement> = {
  dashboard: DashboardPanel,
  market: MarketPanel,
  bess: BessPanel,
  automations: AutomationsPanel,
  alerts: AlertsPanel,
};

export function PlatformPreview() {
  const [active, setActive] = useState<PreviewKey>("dashboard");
  const ActivePanel = PANELS[active];

  return (
    <div className="w-full max-w-[980px] overflow-hidden rounded-3xl border border-slate-800 bg-[#0B1020] shadow-2xl">
      <BrowserBar />

      <div className="w-full overflow-hidden" style={{ height: CANVAS_HEIGHT * SCALE }}>
        <div
          className="flex origin-top-left bg-[#050816] text-white"
          style={{ width: CANVAS_WIDTH, height: CANVAS_HEIGHT, transform: `scale(${SCALE})` }}
        >
          <PreviewSidebar active={active} onSelect={setActive} />

          <main className="flex-1 overflow-hidden p-4">
            <ActivePanel />
          </main>
        </div>
      </div>
    </div>
  );
}
