"use client";

import { Suspense, useState, type ReactElement } from "react";

import type { EnergyFlowPoint, ForecastSummary } from "@/app/[locale]/(platform)/dashboard/dashboard-data";
import { BatteryOptimizationCard } from "@/components/automations/BatteryOptimizationCard";
import { ChartSkeleton } from "@/components/charts/ChartSkeleton";
import CardHeader from "@/components/dashboard/CardHeader";
import { EnergyFlowDiagram } from "@/components/dashboard/EnergyFlowDiagram";
import { ForecastCard } from "@/components/dashboard/ForecastCard";
import { InvertersCard } from "@/components/dashboard/InvertersCard";
import { DynamicLiveEnergyChart } from "@/components/dashboard/LiveEnergyChart.dynamic";
import { WeatherCard } from "@/components/dashboard/WeatherCard";
import { MarketDistribution } from "@/components/market/MarketDistribution";
import { MarketEventLog } from "@/components/market/MarketEventLog";
import { MarketInfo } from "@/components/market/MarketInfo";
import { MarketInsights } from "@/components/market/MarketInsights";
import { DynamicMarketPriceChart } from "@/components/market/MarketPriceChart.dynamic";
import { MarketSummaryCard } from "@/components/market/MarketSummaryCard";
import { PageContainer } from "@/components/platform/layout/PageContainer";
import { PreviewSidebar, type PreviewKey } from "@/components/sections/preview/PreviewSidebar";
import Card from "@/components/ui/Card";
import {
  SNAPSHOT_DASHBOARD_DATA,
  SNAPSHOT_MARKET_DATA,
  SNAPSHOT_PRODUCTION_DATA,
} from "@/lib/demo/landing-snapshot";
import { useElementWidth } from "@/lib/hooks/useElementWidth";
import type { SolarWeather, SolarWeatherPoint } from "@/lib/weather/openMeteo";

import BrowserBar from "../dashboard/BrowserBar";

/**
 * Hero browser-mockup preview. A self-contained, client-side "embedded
 * product preview": `PreviewSidebar` (a marketing-only visual copy of the
 * real `AppSidebar`, not the real component) switches which panel is shown
 * below purely via local React state — the browser window itself never
 * navigates anywhere. Each panel reuses the real presentational Dashboard/
 * Market/Automations components (`WeatherCard`, `MarketEventLog`,
 * `MarketInsights`, `BatteryOptimizationCard`, `Card`/`CardHeader`, ...) fed
 * a frozen, one-time snapshot of real production data
 * (`lib/demo/landing-snapshot.ts`, generated by
 * `scripts/create-landing-snapshot.ts` — see that script's doc comment) —
 * this is what keeps the mockup's colors/legends/tooltips/spacing
 * automatically identical to production instead of a hand-copied, easily
 * stale second implementation. This file never fetches data, calls Huawei/
 * ENTSO-E, or touches a database — it only imports literal, already-
 * computed values (plus one hand-written illustrative sample for the
 * Solar Weather widget, which has no per-organization data to freeze — see
 * `buildSampleSolarWeather` below). Market Price Optimization has no
 * standalone-safe presentational component (the real
 * `MarketPriceOptimizationCard` is wired to a live server action), so that
 * one card's markup is a static, non-interactive visual copy of it instead
 * (`MarketPriceOptimizationPreviewCard` below) — no state, no handler.
 *
 * The whole sidebar+content canvas renders at a real, natural desktop size
 * and is scaled down with a CSS transform to fit the hero's fixed-width
 * mockup frame — a real screenshot's proportions, not the actual layout
 * being squeezed through narrower responsive breakpoints.
 */

const data = SNAPSHOT_DASHBOARD_DATA;
const market = SNAPSHOT_MARKET_DATA;
const production = SNAPSHOT_PRODUCTION_DATA;

const CANVAS_WIDTH = 1440;
// +~13% over the original 860px canvas — same width, same SCALE (no zoom
// change), just more vertical room so cards breathe like the real app.
const CANVAS_HEIGHT = 970;
const SCALE = 980 / CANVAS_WIDTH;

const currentPriceTrend = { direction: "up" as const, label: "+4.20 EUR/MWh" };

const nowAnnotation =
  data.energyFlow.available && production.currentExport.available
    ? `${data.energyFlow.pvKw} kW prod · ${production.currentExport.kw} kW export`
    : undefined;

/**
 * The real `WeatherCard`'s `SolarWeather` prop has no per-organization
 * data this file can freeze (there is no `Plant.latitude`/`longitude` for
 * a marketing snapshot, and calling the real `getSolarWeather` here would
 * mean this file performing live I/O, which it deliberately never does —
 * see this file's top doc comment). This is hand-written illustrative
 * sample data instead, shaped exactly like `SolarWeather` so it renders
 * through the identical, unmodified `WeatherCard` component production
 * uses. Built from `Date.now()` (not a frozen date) so its 8-hour forecast
 * strip — `WeatherCard` itself filters to points at/after the real current
 * instant — always has 8 upcoming hours to show, regardless of when a
 * visitor loads the landing page.
 */
function buildSampleSolarWeather(): SolarWeather {
  const now = new Date();
  const CURRENT_IRRADIANCE = 420;
  const CURRENT_CLOUD_COVER = 35;
  const CURRENT_TEMPERATURE = 29;
  const CURRENT_WIND_SPEED = 2.1;

  // A plausible midday irradiance/cloud-cover arc, not a live reading —
  // the first entry matches the CURRENT_* constants above. weatherCode 1
  // ("mainly clear") throughout - none of the icon-override code ranges
  // (see WeatherCard.tsx's weatherCodeOverride), so this arc's icons come
  // purely from cloudCover, same as the real WeatherCard's default path.
  const SAMPLE_WEATHER_CODE = 1;
  const hourlyTemplate: Array<{ irradiance: number; cloudCover: number }> = [
    { irradiance: CURRENT_IRRADIANCE, cloudCover: CURRENT_CLOUD_COVER },
    { irradiance: 560, cloudCover: 28 },
    { irradiance: 650, cloudCover: 20 },
    { irradiance: 720, cloudCover: 15 },
    { irradiance: 760, cloudCover: 12 },
    { irradiance: 740, cloudCover: 15 },
    { irradiance: 690, cloudCover: 18 },
    { irradiance: 610, cloudCover: 22 },
  ];

  const hourly: SolarWeatherPoint[] = hourlyTemplate.map((point, index) => ({
    time: new Date(now.getTime() + index * 60 * 60 * 1000),
    irradiance: point.irradiance,
    cloudCover: point.cloudCover,
    temperature: CURRENT_TEMPERATURE + index * 0.3,
    windSpeed: CURRENT_WIND_SPEED + index * 0.1,
    weatherCode: SAMPLE_WEATHER_CODE,
  }));

  return {
    current: {
      irradiance: CURRENT_IRRADIANCE,
      cloudCover: CURRENT_CLOUD_COVER,
      temperature: CURRENT_TEMPERATURE,
      windSpeed: CURRENT_WIND_SPEED,
      weatherCode: SAMPLE_WEATHER_CODE,
    },
    hourly,
  };
}

const SAMPLE_SOLAR_WEATHER = buildSampleSolarWeather();

/**
 * Same reasoning as `buildSampleSolarWeather` above — the real
 * `ForecastSummaryPanel`/Live Energy forecast overlay has no
 * per-organization data this file can freeze, and computing the real
 * forecast here would mean this file performing live I/O (weather fetch,
 * historical DB reads), which it deliberately never does. Hand-written
 * illustrative sample data instead — a plausible ramp-up-to-peak-then-
 * decline curve appended onto the frozen `data.chartSeries` as its
 * `forecastPvKw` field (past half `null`, future half a forecast value),
 * plus a matching sample `ForecastSummary`, shaped exactly like production
 * so both render through the identical, unmodified `LiveEnergyChart`/
 * `ForecastSummaryPanel` components.
 *
 * Anchored to `data.chartSeries`'s own last timestamp, not `Date.now()`:
 * `data` is `SNAPSHOT_DASHBOARD_DATA`, frozen at whatever moment
 * `scripts/create-landing-snapshot.ts` last ran (see `lib/demo/
 * landing-snapshot.ts`'s `selectedDate`), which drifts further from the
 * real "now" every day this snapshot isn't refreshed. Anchoring the
 * forecast overlay to the real wall clock instead opened an ever-growing
 * gap between the frozen day's timestamps and "today" - the chart's X axis
 * (`domain={["dataMin", "dataMax"]}`) stretched to cover that whole gap,
 * squeezing the actual plotted line into a sliver at one edge. Anchoring to
 * the snapshot's own last point keeps the forecast contiguous with the
 * historical line regardless of snapshot age, at the cost of the real
 * `LiveEnergyChart`'s live "NOW" reference line never landing inside this
 * frozen demo's date range - an acceptable trade for a static preview, and
 * not something fixable here without changing that shared component.
 */
function buildSampleForecastChartSeries(): EnergyFlowPoint[] {
  const futureShape = [116, 110, 100, 88, 72, 55, 38, 22, 10, 3];
  const lastHistoricalTime =
    data.chartSeries.length > 0
      ? data.chartSeries[data.chartSeries.length - 1]!.time
      : Date.now();

  const forecastByTime = new Map<number, number>(
    futureShape.map((kw, index) => [lastHistoricalTime + index * 15 * 60 * 1000, kw]),
  );

  const merged = data.chartSeries.map((point) => ({
    ...point,
    forecastPvKw: forecastByTime.get(point.time) ?? null,
  }));

  const extraPoints = futureShape
    .map((kw, index) => ({ time: lastHistoricalTime + index * 15 * 60 * 1000, kw }))
    .filter((point) => point.time > lastHistoricalTime)
    .map((point) => ({
      time: point.time,
      pvKw: null,
      consumptionKw: null,
      gridImportKw: null,
      gridExportKw: null,
      forecastPvKw: point.kw,
    }));

  return [...merged, ...extraPoints];
}

function buildSampleForecastSummary(): ForecastSummary {
  return {
    dailyForecastKwh: 2296.8,
    weeklyForecastKwh: 14840.2,
    monthlyForecastKwh: 58154.7,
    dailyPeakKw: 281.3,
    confidence: "HIGH",
    modelVersion: "pv-forecast-v1",
    weatherSource: "open-meteo",
    issuedAt: new Date(),
  };
}

const SAMPLE_FORECAST_CHART_SERIES = buildSampleForecastChartSeries();
const SAMPLE_FORECAST_SUMMARY = buildSampleForecastSummary();

function DashboardPanel() {
  return (
    <PageContainer className="space-y-3">
      <section className="grid gap-2.5 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-6">
        <MarketSummaryCard eyebrow="Yield Today" value={data.kpis.producedTodayKwh?.toFixed(1)} valueUnit="kWh" />
        <MarketSummaryCard eyebrow="Total Yield" value={data.kpis.totalYieldKwh ? (data.kpis.totalYieldKwh / 1000).toFixed(1) : undefined} valueUnit="MWh" />
        <MarketSummaryCard eyebrow="Consumption Today" value={data.kpis.consumedTodayKwh?.toFixed(1)} valueUnit="kWh" />
        <MarketSummaryCard eyebrow="Consumed from PV" value={data.kpis.consumedFromPvKwh?.toFixed(1)} valueUnit="kWh" />
        <MarketSummaryCard eyebrow="Fed to Grid" value={data.kpis.exportedTodayKwh?.toFixed(1)} valueUnit="kWh" />
        <MarketSummaryCard eyebrow="From Grid" value={data.kpis.importedTodayKwh?.toFixed(1)} valueUnit="kWh" />
      </section>

      <section className="grid gap-2.5 lg:grid-cols-[30%_1fr]">
        <div className="flex flex-col rounded-2xl border border-white/10 bg-white/[0.03] p-3.5 shadow-[0_1px_0_0_rgba(255,255,255,0.03)_inset,0_12px_28px_-16px_rgba(0,0,0,0.55)] sm:p-4">
          <div>
            <h2 className="text-sm font-semibold text-white">System Overview</h2>
            <p className="mt-0.5 text-xs text-slate-500">Real-time energy flow</p>
          </div>
          <div className="mt-2 min-h-0 flex-1">
            <EnergyFlowDiagram flow={data.energyFlow} isToday={data.isToday} />
          </div>
        </div>

        <div className="flex flex-col rounded-2xl border border-white/10 bg-white/[0.03] p-3.5 shadow-[0_1px_0_0_rgba(255,255,255,0.03)_inset,0_12px_28px_-16px_rgba(0,0,0,0.55)] sm:p-4">
          <div>
            <h2 className="text-sm font-semibold text-white">Live Energy</h2>
            <p className="mt-0.5 text-xs text-slate-500">Today&apos;s production, consumption, and grid exchange</p>
          </div>
          <div className="mt-2.5 h-[320px]">
            <Suspense fallback={<ChartSkeleton />}>
              <DynamicLiveEnergyChart data={SAMPLE_FORECAST_CHART_SERIES} nowAnnotation={data.nowAnnotation} />
            </Suspense>
          </div>
        </div>
      </section>

      <section className="grid gap-2.5 lg:grid-cols-2 xl:grid-cols-4">
        <InvertersCard inverters={data.inverters} />
        <WeatherCard weather={SAMPLE_SOLAR_WEATHER} />
        <ForecastCard summary={SAMPLE_FORECAST_SUMMARY} />
        <MarketEventLog entries={data.eventLog} />
      </section>
    </PageContainer>
  );
}

function MarketPanel() {
  return (
    <PageContainer className="space-y-3">
      <section className="grid gap-2.5 sm:grid-cols-2 xl:grid-cols-5">
        <MarketSummaryCard
          eyebrow="Today's Revenue"
          value={data.kpis.revenue.available ? data.kpis.revenue.revenueEur.toFixed(2) : undefined}
          valueUnit="EUR"
          rows={
            data.kpis.revenue.available
              ? [
                  { label: "Exported today", value: `${data.kpis.revenue.exportedKwh.toFixed(2)} kWh` },
                  {
                    label: "Average selling price",
                    value:
                      data.kpis.revenue.averagePriceEurPerMwh !== null
                        ? `${data.kpis.revenue.averagePriceEurPerMwh.toFixed(2)} EUR/MWh`
                        : "—",
                  },
                ]
              : undefined
          }
        />

        <MarketSummaryCard
          eyebrow="Current Price"
          value={market.summary.currentPrice?.value.toString()}
          valueUnit="EUR/MWh"
          caption={market.summary.currentPrice?.intervalLabel}
          trend={currentPriceTrend}
        />

        <MarketSummaryCard
          eyebrow="Current Export"
          value={production.currentExport.available ? production.currentExport.kw.toString() : undefined}
          valueUnit="kW"
        />

        {/*
          Presentation-only override for the frozen landing-page snapshot:
          the real production.configuredExportModeLabel is "Unavailable"
          (this plant's real Huawei configuration-mode endpoint is
          documented as failing, see get-export-control-status.ts) —
          genuinely correct for the live product, but not what this
          marketing snapshot should show. Same two-row `rows` shape
          `market/page.tsx`'s own (private) `configuredModeStatus` produces
          — "Enabled"/"Current Mode" in emerald, exactly like a real
          healthy day — not the old single-dot "Huawei configuration
          endpoint" style Market itself stopped showing. Only this card's
          display is overridden; the frozen data itself
          (lib/demo/landing-snapshot.ts) is untouched.
        */}
        <MarketSummaryCard
          eyebrow="Configured Mode"
          rows={[
            { label: "Automation", value: "Enabled", valueColorClass: "text-emerald-400" },
            { label: "Current Mode", value: "No Limit", valueColorClass: "text-emerald-400" },
          ]}
        />

        {/*
          Same derivation as `market/page.tsx`'s own `thresholdStatusDot`:
          current price vs. the configured threshold, not import-
          completeness (`marketStatus.healthy`, which answers a different
          question). For this frozen snapshot, currentPrice (100.01) is
          above the threshold (15), so this correctly reads "Healthy" —
          same value the old code happened to show, now derived correctly.
        */}
        <MarketSummaryCard
          eyebrow="Threshold"
          value={market.threshold.minimumExportPrice.toString()}
          valueUnit={`${market.threshold.currency}/MWh`}
          caption="Minimum profitable price"
          statusDot={
            market.summary.currentPrice !== null
              ? market.summary.currentPrice.value >= market.threshold.minimumExportPrice
                ? { colorClass: "bg-emerald-400", label: "Healthy" }
                : { colorClass: "bg-amber-400", label: "Below threshold" }
              : undefined
          }
        />
      </section>

      <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-3.5 shadow-[0_1px_0_0_rgba(255,255,255,0.03)_inset,0_12px_28px_-16px_rgba(0,0,0,0.55)] sm:p-4">
        <div>
          <h2 className="text-sm font-semibold text-white">Price &amp; Export</h2>
          <p className="mt-0.5 text-xs text-slate-500">Electricity price and recommended export windows</p>
        </div>

        <div className="mt-2.5 h-[260px]">
          <Suspense fallback={<ChartSkeleton />}>
            <DynamicMarketPriceChart
              series={market.series}
              thresholdPrice={market.threshold.minimumExportPrice}
              nowAnnotation={nowAnnotation}
              settlementEnergySeries={production.settlementEnergySeries.map(({ intervalStart, exportedKwh }) => ({
                intervalStart,
                exportedKwh,
              }))}
              installedCapacityKw={production.installedCapacityKw}
            />
          </Suspense>
        </div>
      </section>

      <section className="grid gap-2.5 lg:grid-cols-2 xl:grid-cols-4">
        <MarketEventLog entries={market.eventLog} />
        <MarketInsights insights={market.insights} />
        <MarketDistribution buckets={market.distribution} />
        <MarketInfo country={market.summary.marketStatus.country} source={market.summary.marketStatus.source} lastUpdateLabel={null} />
      </section>
    </PageContainer>
  );
}

function BessPanel() {
  return (
    <PageContainer>
      <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4 shadow-[0_1px_0_0_rgba(255,255,255,0.03)_inset,0_12px_28px_-16px_rgba(0,0,0,0.55)]">
        <p className="text-[11px] font-medium uppercase tracking-wider text-slate-500">Status</p>
        <p className="mt-3 text-sm text-slate-400">No battery systems connected.</p>
        <p className="mt-1 max-w-md text-xs text-slate-600">
          Voltessa automatically detects and manages battery assets when available.
        </p>
      </div>
    </PageContainer>
  );
}

/**
 * A static visual copy of the real `MarketPriceOptimizationCard`'s markup
 * (same `Card`/`CardHeader`, same toggle/input/button classes) — not that
 * component itself, since the real one is wired to a live server action
 * (`updateMarketPriceAutomation`) that must never run from the public
 * landing page. Static and non-interactive by design — no state, no
 * handler, no `onClick`.
 */
function MarketPriceOptimizationPreviewCard() {
  return (
    <Card className="p-6">
      <CardHeader
        title="Market Price Optimization"
        subtitle="Automatically stops exporting electricity to the grid when the market price falls below your threshold, and resumes automatically once the price recovers."
      />

      <div className="flex items-center justify-between rounded-xl border border-white/10 bg-white/5 px-4 py-3">
        <span className="text-sm text-white/80">Enable automation</span>

        <span className="relative inline-flex h-6 w-11 shrink-0 items-center rounded-full bg-emerald-400/80">
          <span className="inline-block h-5 w-5 translate-x-5 transform rounded-full bg-white" />
        </span>
      </div>

      <div className="mt-4">
        <span className="block text-sm text-white/80">
          When electricity price falls below (€/MWh)
        </span>

        <div className="mt-2 w-40 rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-white">
          15.00
        </div>
      </div>

      <span className="mt-6 inline-block rounded-xl bg-blue-600 px-5 py-2 text-sm font-medium text-white">
        Save
      </span>
    </Card>
  );
}

/** Same structure as the real `app/(platform)/automations/page.tsx`: an intro line, then the two cards stacked full-width. */
function AutomationsPanel() {
  return (
    <PageContainer className="space-y-3">
      <p className="text-white/60">Configure automated rules for this plant.</p>

      <div className="space-y-5">
        <MarketPriceOptimizationPreviewCard />
        <BatteryOptimizationCard />
      </div>
    </PageContainer>
  );
}

function AlertsPanel() {
  return (
    <PageContainer>
      <section>
        <p className="text-white/60">Review operational alerts and important platform events.</p>
      </section>
    </PageContainer>
  );
}

const PANELS: Record<PreviewKey, () => ReactElement> = {
  dashboard: DashboardPanel,
  market: MarketPanel,
  bess: BessPanel,
  automations: AutomationsPanel,
  alerts: AlertsPanel,
};

export function PlatformPreview() {
  const [active, setActive] = useState<PreviewKey>("dashboard");
  const ActivePanel = PANELS[active];

  // Responsive Design Sprint: the canvas below is a fixed CANVAS_WIDTH x
  // CANVAS_HEIGHT layout, scaled down with a CSS transform to look like a
  // real screenshot rather than squeezing through narrower responsive
  // breakpoints (see this file's top doc comment). That scale used to be
  // the single constant `SCALE` (980 / CANVAS_WIDTH) — correct only for
  // exactly the 980px-wide desktop hero slot, and severely CLIPPED (not
  // just shrunk) on any narrower viewport, since `overflow-hidden` on the
  // wrapper below cuts off whatever the transform doesn't shrink to fit.
  // `frameWidth` is this component's own real rendered width (via
  // ResizeObserver, same primitive `ChartFrame` uses for chart tick
  // density), so the scale always matches the actual space available —
  // never more than the original `SCALE` (this frame is capped at
  // `max-w-[980px]`, so `frameWidth` never exceeds 980px either), so
  // desktop is unaffected; narrower frames shrink further instead of
  // clipping.
  const [frameRef, frameWidth] = useElementWidth<HTMLDivElement>();
  const scale = frameWidth > 0 ? frameWidth / CANVAS_WIDTH : SCALE;

  return (
    <div
      ref={frameRef}
      className="w-full max-w-[980px] overflow-hidden rounded-3xl border border-slate-800 bg-[#0B1020] shadow-2xl"
    >
      <BrowserBar />

      <div className="w-full overflow-hidden" style={{ height: CANVAS_HEIGHT * scale }}>
        <div
          className="flex origin-top-left bg-[#050816] text-white"
          style={{ width: CANVAS_WIDTH, height: CANVAS_HEIGHT, transform: `scale(${scale})` }}
        >
          <PreviewSidebar active={active} onSelect={setActive} />

          <main className="flex-1 overflow-hidden p-4">
            <ActivePanel />
          </main>
        </div>
      </div>
    </div>
  );
}
